Added Terminal support for `%override`
lark-parser/lark pull request #804
Opened 2020-12-25 00:29 UTC by MegaIng

First point in #803

2020-12-25 23:16 UTC, MegaIng commented
`lark.lark` update in #805

2020-12-25 23:39 UTC, erezsh requested changes

2020-12-25 23:39 UTC, erezsh commented on lark/load_grammar.py
> +                    if len(r.children) == 2:
These 4 lines should be a extracted into a function

2020-12-25 23:39 UTC, erezsh commented on docs/grammar.md
> +Override a rule or terminals, affecting all references to it, even in imported grammars.
terminal, singular.

2021-01-26 22:17 UTC, erezsh commented
Outdated

2021-01-26 22:17 UTC, closed without merging