Fixes to static/class methods handling when v_args is used
lark-parser/lark pull request #999
Opened 2021-09-14 22:55 UTC by ornariece

Static/class methods are now handled properly when v_args is used.
I've listed the problematic usecases in this example:

```python
from lark.visitors import Transformer, v_args

class C:
    def method1(self):
        pass

    c = 1

    @classmethod
    def method2(cls):
        return cls.c

@v_args(inline=True)
class T(Transformer):
    @staticmethod
    def method1():
        pass

    t = 2

    @classmethod
    def method2(cls):
        return cls.t

    method3 = C.method2
    method4 = C.method1

T.method1()
T().method1()
T.method2()
T().method2()
T.method3()
T().method3()
T().method4()
```

2021-09-14 23:10 UTC, MegaIng requested changes

2021-09-14 23:11 UTC, MegaIng commented on lark/visitors.py
> +            static = isinstance(cls.__dict__[name], (staticmethod, classmethod)) or ismethod(cls.__dict__[name])
E.g. we should probably delegate to the underlying functions `__get__` function instead of trying to be smart with what we are doing.

2021-09-14 23:24 UTC, ornariece commented on lark/visitors.py
> +            static = isinstance(cls.__dict__[name], (staticmethod, classmethod)) or ismethod(cls.__dict__[name])
> for example it also fails for custom types with a `__call__` method

not sure why this would fail, can you give me an example?

2021-09-14 23:56 UTC, MegaIng commented on lark/visitors.py
> +            static = isinstance(cls.__dict__[name], (staticmethod, classmethod)) or ismethod(cls.__dict__[name])
```

class SomethingCallable():
    def __call__(*args):
        print(args)

@v_args(inline=True)
class T(Transformer):
    something = SomethingCallable()
```

fails with `AttributeError: 'SomethingCallable' object has no attribute '__func__'`

2021-09-15 14:02 UTC, MegaIng commented on lark/visitors.py
> +            static = isinstance(cls.__dict__[name], (staticmethod, classmethod)) or ismethod(cls.__dict__[name])
@ornariece Could you take a look at PR #1000 and look if you find more edge cases?

2021-09-16 18:59 UTC, ornariece commented
better fix made in #1000

2021-09-16 18:59 UTC, closed without merging